---
# MIT License
#
# Copyright (c) 2022 FABRIC Testbed
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Author: Liang Zhang (lzhang9@es.net)
# /tasks/create-token.yml
#

- name: Establish API session using token-based access
  ansible.builtin.uri:
    url: "{{ base_url }}/v1/sessions/access"
    headers:
      Accept: application/json
      x-api-key: "{{ api_access_key }}"
      content-type: application/json
    status_code: 200
    method: POST
    validate_certs: no
  register: access_response
  
- name: Print access response
  debug:
    msg: "{{ access_response }}"
    
- name: Save refresh token
  set_fact:
    refresh_token: "{{ access_response.cookies.arroyoRefreshToken }}"
    
- name: Print refresh token    
  debug:
    msg: "{{ refresh_token }}"
 
- name: Exchange refresh token for new refresh and bearer tokens
  ansible.builtin.uri:
    url: "{{ base_url }}/v1/sessions/refresh"
    headers:
      Accept: application/json
      Cookie: arroyoRefreshToken="{{ refresh_token }}"
      content-type: application/json
    status_code: 200
    method: GET
    validate_certs: no
  register: refresh_response
  
- name: Print refresh response
  debug:
    msg: "{{ refresh_response }}"
    
- name: Save bearer token
  set_fact:
    bearer_token: "{{ refresh_response.authorization }}"
    
- name: Print bearer token    
  debug:
    msg: "{{ bearer_token }}"
