---
# MIT License
#
# Copyright (c) 2022 FABRIC Testbed
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Author: Liang Zhang (lzhang9@es.net)
# /tasks/create-spaces.yml
#

#
# Create virtual space
#
- include_tasks: create-space.yml

#- name: Save virtual space id
#  set_fact:
#    virtual_space_id: "bae32910-6c3b-4e49-bf7c-c992ea29eb78"

#
# Create virtual router
#
- include_tasks: create-router.yml

#- name: Save virtual router id
#  set_fact:
#    virtual_router_id: "d3f1e7e1-f266-4af9-82f1-a358ac03bf05"

#
# Create L3 connection
#
- include_tasks: create-l3connection.yml
  vars:
    l3connection: "{{ item }}"
  loop: "{{ opargs }}"