---
# MIT License
#
# Copyright (c) 2022 FABRIC Testbed
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Author: Liang Zhang (lzhang9@es.net)
# /tasks/create-space.yml
#

- name: Construct request data
  set_fact:
    create_space_request: '{"title": "{{ name }}", "notes": "", "ownerPath": "{{ ownerPath }}"}'

#- name: Print create space request
#  debug:
#    msg: "{{ create_space_request | to_nice_json }}"

- name: Create a virtual space endpoint
  ansible.builtin.uri:
    url: "{{ base_url }}/v1/virtualnetworks/spaces"
    headers:
      Accept: application/json
      Authorization: "{{ bearer_token }}"
      content-type: application/json
    body: "{{ create_space_request | to_nice_json }}"
    status_code: [200, 303]
    method: POST
    validate_certs: no
  register: create_space_response
  
#- name: Print create space response
#  debug:
#    msg: "{{ create_space_response }}"
    
- name: Parse create space response
  set_fact:
    location_list: "{{ create_space_response.location | split('/') }}"
    
- name: Save virtual space id
  set_fact:
    virtual_space_id: "{{ location_list[-1] }}"

- name: Print virtual space id
  debug:
    msg: "{{ virtual_space_id }}"
