---
# MIT License
#
# Copyright (c) 2022 FABRIC Testbed
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Author: Liang Zhang (lzhang9@es.net)
# /tasks/search-space.yml
#
# This file search the spaces with titles as "name" and return the list of those
# space ids.
# - input: name
# - return: space ids
#
- name: List virtual spaces
  ansible.builtin.uri:
    url: "{{ base_url }}/v1/virtualnetworks/spaces"
    headers:
      Accept: application/json
      Authorization: "{{ bearer_token }}"
      content-type: application/json
    status_code: [200, 303]
    method: GET
    validate_certs: no
  register: list_space_response
  
#- name: print response
#  debug:
#    msg: "{{ list_space_response }}"

- name: search virtual space
  set_fact:
    space_id_list: "{{ space_id_list | default([]) + [space_item.virtualSpaceId] }}"
  when:
    - space_item.title == name
  with_items: "{{ list_space_response.json.spaces }}"
  loop_control:
    loop_var: space_item
  
- name: print list of spaces having the title as name
  debug:
    msg: "{{ space_id_list }}"
  when: space_id_list is defined