---
# /tasks/main.yml
#
- name: Set a variable
  ansible.builtin.set_fact:
    vm_prov_op: "{{ vm_prov_op }}"

- name: Create a VM
  os_server:
    state: present
    auth:
      auth_url: "{{ auth_url }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      username: "{{ username }}"
    name: "{{ vmname }}"
    image: "{{ image }}"
    key_name: "{{ key_name }}"
    timeout: 200
    flavor: "{{ flavor }}"
    availability_zone: "{{ availability_zone }}"
    nics:
      - net-name: "{{ net_name }}"
    security_groups: "{{ security_group }}"
  when: vm_prov_op == "create"

- name: Attach a floating IP to the instance
  os_floating_ip:
    auth:
      auth_url: "{{ auth_url }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      username: "{{ username }}"
    server: "{{ vmname }}"
    state: present
    reuse: yes
    wait: true
    timeout: 200
    network: "{{ ext_network }}"
  when: vm_prov_op == "attach_fip"

- name: Delete a VM
  os_server:
    state: absent
    auth:
      auth_url: "{{ auth_url }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      username: "{{ username }}"
    name: "{{ vmname }}"
  when: vm_prov_op == "delete"
