---
- hosts: localhost
#- hosts: fabric_site_al2s
  tasks:
    - name: message
      debug:
        msg: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}"

    - name: show HOME
      debug: var=ansible_facts.env.HOME

  roles:
    - { role: ./roles/virtualnetworks_provisioning }
