---
# file: fpga_provisioning.yml

- hosts:
    - "{{ worker_node_name }}"

  vars:
    domain: "0x0000"
    bus: "0x25"
    slot: "0x0"
    dest_domain: "0x0000"
    dest_bus: "0x00"
    # best to set this high and not worry about collisions
    # must be lower case to match removal
    dest_slot: "0x1a"
    num_pci_functions: 1
    usb_ctrlr_idx: 2
    # default U280 info
    fpga_usb_vendor_id: "0x0403"
    fpga_usb_product_id: "0x6011"
    fpga_dest_usb_bus: "2"
    fpga_dest_usb_port: "2"

  roles:
    - fpga_provisioning