- name: Configure device
  hosts:
    - fabric_site_nso
  connection: local
  gather_facts: no

  vars:
    service: "{{service_type}}"
    action: "{{service_action}}"

  tasks:
  - name: Create idipa service
    nso_config:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      data:
        tailf-ncs:services:
          idipa:idipa:
          - name: "{{ service_name }}"
            group:
              service: service
    when: (service == 'l2ptp' or service == 'l2sts') and action == 'create'

  - name: Create network service
    nso_config:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      data: "{{ data }}"
    when: action == 'create'

  - name: Delete network service
    nso_config:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      data: "{{ data }}"
    when: action == 'delete'

  - name: Delete idipa service
    nso_config:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      data:
        tailf-ncs:services:
          idipa:idipa:
          - name: "{{ service_name }}"
            __state: absent
    when: (service == 'l2ptp' or service == 'l2sts') and atcion == 'create'
