---
# file: worker_libvirt_operations.yml

- hosts: 
    #- "{{ worker_node_name }}"
    - "{{ worker_node_name | default('fabric_site_worker') }}"  # Default to fabric_site_worker if worker_node_name is not provided

  gather_facts: no

  vars:

  roles:
    - worker_libvirt_operations
