---
# MIT License
#
# Copyright (c) 2020 FABRIC Testbed
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Author: Komal Thareja (kthare10@renci.org)
# /tasks/main.yml
#
- name: Reboot the switch
  ansible.builtin.reboot:
  when: operation == "reboot"

- name: Prepare for ONIE reinstall
  block:
    - name: Ensure ONIE boot directory exists
      ansible.builtin.file:
        path: /mnt/onie-boot
        state: directory
        mode: '0755'

    - name: Mount ONIE boot partition
      ansible.builtin.mount:
        path: /mnt/onie-boot
        src: /dev/sda2
        fstype: auto
        state: mounted

    - name: Set ONIE to install mode using GRUB
      ansible.builtin.command: grub-reboot ONIE

    - name: Set ONIE boot mode to install
      ansible.builtin.command: /mnt/onie-boot/onie/tools/bin/onie-boot-mode -o install

    - name: Reboot the system for ONIE install
      ansible.builtin.reboot:
  when: operation == "create"

# Add your additional tasks for updating the system and installing Docker
- name: Add nameservers from inventory to /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ item }}"
    state: present
    create: yes
  with_items: "{{ nameservers.split(',') }}"
  when: nameservers is defined and operation == 'config'
  become: true

- name: Check if freerouter service exists
  shell: systemctl list-unit-files | grep freerouter.service
  register: freerouter_service_check
  ignore_errors: true
  when: operation == 'config'

# Stop the freerouter service
- name: Stop freerouter.service
  shell: systemctl stop freerouter.service
  when: operation == 'config' and freerouter_service_check.rc == 0

# Disable the freerouter service
- name: Disable freerouter.service
  shell: systemctl disable freerouter.service
  when: operation == 'config' and freerouter_service_check.rc == 0

- name: Add authorized SSH key for the user
  lineinfile:
    path: "/home/{{ new_user }}/.ssh/authorized_keys"
    line: "{{ sshkey }}"
    create: yes
    owner: "{{ new_user }}"
    group: "{{ new_user }}"
    mode: '0600'
  when: operation == 'config'

- name: Remove SSH key from authorized_keys
  lineinfile:
    path: "/home/{{ new_user }}/.ssh/authorized_keys"
    state: absent
    line: "{{ sshkey }}"
  when: operation == 'delete'

- name: Lock the user account
  user:
    name: "{{ new_user }}"
    state: present
    password_lock: yes
  when: operation == 'delete'

- name: Kill active SSH sessions for the user
  shell: pkill -u "{{ new_user }}"
  ignore_errors: true
  when: operation == 'delete'