--- 
# /tasks/main.yml
#

- name: Create entry to add/delete device
  template:
    src: device.j2
    dest: /tmp/device.yml
    mode: 0600

- name: Add PCI Card to VM
  ansible.builtin.shell: 
    virsh attach-device {{ kvmguest_name }} /tmp/device.yml --live
  when: add_pcicard == "True"

- name: Remove PCI Card to VM
  ansible.builtin.shell: 
    virsh detach-device {{ kvmguest_name }} /tmp/device.yml --live
  when: add_pcicard == "False"

