---
# /tasks/main.yml
#

- name: Attach a floating IP to the instance
  os_floating_ip:
    auth:
      auth_url: {{ auth_url }}
      password: {{ password }}
      project_name: {{ project_name }}
      username: {{ username }}
    server: {{ name }}
    state: present
    reuse: yes
    wait: true
    timeout: 200
    network: {{ network_name }}

  register: instance_reply

- set_fact:
      workernode_name: "{{ instance_reply.stdout.replace('|', ' ').split()[1] }}"
      kvmguest_name: "{{ instance_reply.stdout.replace('|', ' ').split()[2] }}"
      kvmguest_status: "{{ instance_reply.stdout.replace('|', ' ').split()[3] }}"

