--- 
# /tasks/main.yml
#
# headnode_name, instance_name, pcidevice_address, add_pcidevice
# kvmguest_name, workernode_name
# instance_info ( instance_uuid, workernode, kvmguest_name, kvmguest_status)

- name: Find VM and workernode names
  ansible.builtin.shell: 
     nova list --all --fields=host,instance_name,status | grep $(openstack server list|grep {{ instance_name }} |cut -d ' ' -f2)
  register: instance_reply

- set_fact:
      workernode_name: "{{ instance_reply.stdout.replace('|', ' ').split()[1] }}"
      kvmguest_name: "{{ instance_reply.stdout.replace('|', ' ').split()[2] }}"
      kvmguest_status: "{{ instance_reply.stdout.replace('|', ' ').split()[3] }}"

