---
# /tasks/main.yml
#

- name: Delete a VM
  os_server:
    state: absent
    auth:
      auth_url: {{ auth_url }}
      password: {{ password }}
      project_name: {{ project_name }}
      username: {{ username }}
    name: {{ vmname }}

